# Generated by Django 5.2.4 on 2025-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_aipromptpreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aipromptpreset',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='aipromptpreset',
            name='prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
