# Generated by Django 5.2.4 on 2025-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_content_aipromptpreset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='properties',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
